spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xxxxxx
    url: jdbc:mysql://192.168.18.11/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: xxxx
  mpAppSecret: xxxx
  mchId: xxxx
  mchKey: xxxx
  keyPath: /var/weixin_cert/h5.p12

